# Generated by Django 2.0.13 on 2019-10-26 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록 시간')),
            ],
            options={
                'verbose_name': '장고스타그램 사용자',
                'verbose_name_plural': '장고스타그램 사용자\x1f',
                'db_table': 'ds_user',
            },
        ),
    ]
