# Generated by Django 2.0.13 on 2019-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsuser',
            name='username',
            field=models.CharField(default='test', max_length=128, verbose_name='사용자명'),
            preserve_default=False,
        ),
    ]
