# Generated by Django 2.0.13 on 2019-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsuser', '0002_dsuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='dsuser',
            name='registered_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
    ]
